name = "DataKnots4FHIR"
uuid = "ab76b815-26a5-47b3-ad9d-b1b88f8ee454"
authors = ["Clark C. Evans <cce@clarkevans.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DataKnots = "f3f2b2ad-91c8-5588-b964-d77e2d3bb090"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
DataKnots = "0.10.1"
JSON = "0.21.0"
NarrativeTest = "0.4.1"
julia = "1.3"

[extras]
NarrativeTest = "9563631e-acd4-5dd8-bebb-4cf36518960d"

[targets]
test = ["NarrativeTest"]
